[theme]
base = "light"
primaryColor = "#007f07"
backgroundColor = "#F7F7F4"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A1A14"

[runner]
fastReruns = true
magicEnabled = false

[client]
showErrorDetails = false
toolbarMode = "minimal"